ListaContatos/Models/ContatoModel.cs
namespace ListaContatos.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public string Observacao { get; set; }
    }
}

ListaContatos/Models/ErrorViewModel.cs
namespace ListaContatos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ListaContatos/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace ListaContatos.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar()
        {
            return View();
        }

        public IActionResult ApagarConfirmacao()
        {
            return View();
        }
    }
}

ListaContatos/Controllers/HomeController.cs
using ListaContatos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ListaContatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ListaContatos/Views/Contato/ApagarConfirmacao.cshtml
@{
    ViewData["Title"] = "Confirmação para Apagar o Contato";
}

<div class="text-center">
    <h3>Realmente Deseja Apagar o Contato?</h3>
</div>

<div class="d-grid gap-2">
    <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Apagar">Confirmar Exclusão</a>
    <a class="btn btn-danger" role="button" asp-controller="Contato" asp-action="Index">Cancelar Exclusão</a>
</div>

ListaContatos/Views/Contato/Criar.cshtml
@{
    ViewData["Title"] = "Criar Contato";
}

<div class="text-center">

    <h1 class="display-4">Cadastro de Contato</h1>

</div>


<form>
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" class="form-control" placeholder="Digite o Nome do Contato">
  </div>

  <div class="form-group">
    <label for="nome">Sobrenome</label>
    <input type="text" class="form-control" placeholder="Digite o Sobrenome do Contato">
  </div>

  <div class="form-group">
    <label for="email">E-mail</label>
    <input type="text" class="form-control" placeholder="Digite o E-mail do Contato">
  </div>

  <div class="form-group">
    <label for="celular">Celular</label>
    <input type="text" class="form-control" placeholder="Digite o Número de Celular do Contato">
  </div>

  <div class="form-group">
    <label for="email">Observação</label>
    <input type="text" class="form-control" placeholder="Digite uma Observação">
    <br/>
  </div>

  <div class="d-grid gap-2">
    <button type="submit" class="btn btn-primary button-block">Adicionar</button>
    <a class="btn btn-secondary button-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
  </div>
</form>

ListaContatos/Views/Contato/Editar.cshtml
@{
    ViewData["Title"] = "Editar Contato";
}

<div class="text-center">

    <h1 class="display-4">Edição de Contato</h1>

</div>


<form>
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" class="form-control" placeholder="Digite o Nome do Contato">
  </div>

  <div class="form-group">
    <label for="nome">Sobrenome</label>
    <input type="text" class="form-control" placeholder="Digite o Sobrenome do Contato">
  </div>

  <div class="form-group">
    <label for="email">E-mail</label>
    <input type="text" class="form-control" placeholder="Digite o E-mail do Contato">
  </div>

  <div class="form-group">
    <label for="celular">Celular</label>
    <input type="text" class="form-control" placeholder="Digite o Número de Celular do Contato">
  </div>

  <div class="form-group">
    <label for="email">Observação</label>
    <input type="text" class="form-control" placeholder="Digite uma Observação">
    <br/>
  </div>

  <div class="d-grid gap-2">
    <button type="submit" class="btn btn-primary button-block">Alterar</button>
    <a class="btn btn-secondary button-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
  </div>
</form>

ListaContatos/Views/Contato/Index.cshtml
@{
    ViewData["Title"] = "Listagem de Contatos";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar Novo Contato</a> 
    </div>
    <br/>

    <h1 class="display-4">Listagem de Contatos</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Sobrenome</th>
                <th scope="col">E-mail</th>
                <th scope="col">Celular</th>
                <th scope="col">Observação</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                    <td>Gustavo</td>
                    <td>Silva</td>
                    <td>gustavo@gmail.com</td>
                    <td>47 99433-5131</td>
                    <td>Colega de classe</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                        </div>
                    </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                    <td>Jonas</td>
                    <td>Oliveira</td>
                    <td>jonas@gmail.com</td>
                    <td>47 99433-5132</td>
                    <td>Colega do trabalho</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                        </div>
                    </td>
            </tr>
            <tr>
                <th scope="row">3</th>
                    <td>Lara</td>
                    <td>Bérgamo</td>
                    <td>lara@gmail.com</td>
                    <td>47 99433-5133</td>
                    <td>Vizinha</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                        </div>
                    </td>
            </tr>
            <tr>
                <th scope="row">4</th>
                    <td>Maria</td>
                    <td>Almeida</td>
                    <td>maria@gmail.com</td>
                    <td>47 99433-5134</td>
                    <td>Colega de classe</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                        </div>
                    </td>
            </tr>
            <tr>
                <th scope="row">5</th>
                    <td>Marcos</td>
                    <td>dos Santos</td>
                    <td>marcos@gmail.com</td>
                    <td>47 99433-5135</td>
                    <td>Professor</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                        </div>
                    </td>
            </tr>
        </tbody>
    </table>
</div>

ListaContatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem-Vindo!</h1>
    <p>Sistema de Controle de Contatos<p/>
</div>

<div class="text-center">
    <br/>
    <h2 class="display-6">Vá para a página "Contatos" para gerenciar seus contatos</h2>
</div>

ListaContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lista de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ListaContatos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lista de Contatos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Lista de Contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>